### ISSUE TITLE
Preset Saving not functioning correctly

### ISSUE THREAD

**Issue by Dataweaver42** [Perdition-117/COM3D2.DressCode#1]
When I attempt to use Pre.Save while editing a DressCode costume, the costume that gets saved isn't the current state of the costume; it's the maid's standard costume.

**Comment by Perdition-117** [comment]
I think I know what's going on. I'll check it out.

**Comment by Dataweaver42** [comment]
Thanks.  This and #5 are the only actual problems I've come across; the rest of my posts are more along the lines of "wouldn't it be nice if..."
