### ISSUE TITLE
Dance uniforms not being used

### ISSUE THREAD

**Issue by Dataweaver42** [Perdition-117/COM3D2.DressCode#10]
I've tried two dances — one regular, one pole dance — and in both cases the maids danced in their regular attire rather than the dancing attire they were supposed to be in. 

Same problem with Yotogi. 

Private Mode and Honeymoon working fine.

**Comment by Perdition-117** [comment]
Given your other issue regarding resetted settings, I now suspect you may have had a full reset. The thumbnails are stored separately and may lead you to assume you have those configured.

Please try creating new dance and yotogi uniforms to see if the issue persists.

**Comment by Dataweaver42** [comment]
I have recreated the costumes, but the problem persists. However, I'm only
having this problem with maids that I created DressCodes for under v1.00;
new maid are working just fine. It's as if the old maids are permanently
stuck in Default for those DressCodes that predate the update.

Actually, it's more interesting than that: when I use a mixture of new
maids and old maids in a dance, even the new maid is in her Default
costume. And it doesn't even matter if I created any DressCodes for any of
the old maids in the mix.

**Comment by Perdition-117** [comment]
I see. There could be an error occuring, preventing outfit changes from happening. Could you look out for red messages in the BepInEx console and/or submit your game log when this has happened? And perhaps your configuration, too? `BepInEx\config\net.perdition.com3d2.dresscode.xml`

**Comment by Dataweaver42** [comment]
Ok, I'll do that.

**Comment by Dataweaver42** [comment]
[output_log.txt](https://github.com/Perdition-117/COM3D2.DressCode/files/12690021/output_log.txt)

**Comment by Perdition-117** [comment]
Ok, I can confirm that dance outfits are not working.

Cannot confirm an issue with yotogi, however. Which yotogi variant?

**Comment by Dataweaver42** [comment]
Hmm… it may be that I was using Memory Mode to test it out. I'll double
check when I get home; I should have an answer for you in about an hour.

**Comment by Dataweaver42** [comment]
Nope. The following log describes what happened when I tried to take one of the old maids into a Yotogi scene:
[output_log.txt](https://github.com/Perdition-117/COM3D2.DressCode/files/12693111/output_log.txt)

**Comment by Dataweaver42** [comment]
I _was_ able to use "Change Costume" to get her "into uniform" once I was in the Yotogi; but it used to be that that would happen automatically.

**Comment by Dataweaver42** [comment]
Further data: it looks like the problem is with the number of dancers. The dancing outfits are showing up fine when there's just one performer; but when there are two or more, there's a problem.

**Comment by Dataweaver42** [comment]
The Private Mode costume didn't get used for the end-of-the-day and beginning-of-the-next-day scenes. This may be similar to the “between dances” scenes that I mentioned earlier; but I wanted it to be on record for future reference.

**Comment by Perdition-117** [comment]
Yes, those scenes suffer from the same issue, unfortunately.

**Comment by Dataweaver42** [comment]
Okay; turns out that I only thought I had the Yotogi costumes set. There's no problem there; only with the multi-maid Dances.

**Comment by Perdition-117** [comment]
Alright, great!

Please try this version. I had to revert some things, which theoretically could affect dress coding of the other scenes, but I think it should be fine.
[COM3D2.DressCode.zip](https://github.com/Perdition-117/COM3D2.DressCode/files/12693890/COM3D2.DressCode.zip)

**Comment by Dataweaver42** [comment]
Much better, thanks.

And thanks to your warning, I was able to use v1.10's newly functioning
Pre.Save feature to save the dance outfits before trying the version that
you just offered. The settings _did_ get reset, but I lost nothing.

**Comment by Dataweaver42** [comment]
I'm considering this issue to be resolved.
