### ISSUE TITLE
DressCode available in “Manage CM3D2”

### ISSUE THREAD

**Issue by Dataweaver42** [Perdition-117/COM3D2.DressCode#11]
When you link COM3D2 to CM3D2, you not only gain the ability to transfer maids over, but you're also given a button on the main screen that mostly replicates CM3D2 in COM3D2. When I do this, I find the DressCode button on the main screen for the CM3D2 simulator. It works, too — except that when I try to leave DressCode, it chokes.

**Comment by Perdition-117** [comment]
I will try to remove the button from CM management. Would you try this and verify that it does so, and reappears when you return to COM?

[COM3D2.DressCode.zip](https://github.com/Perdition-117/COM3D2.DressCode/files/12688969/COM3D2.DressCode.zip)

**Comment by Dataweaver42** [comment]
Which directory should I drop it in?

**Comment by Perdition-117** [comment]
`BepInEx\plugins`, replacing the existing file.

**Comment by Dataweaver42** [comment]
Please stand by. I've dropped the file into the folder, and am restarting
the game; but given how many mods I've got going, starting up the game
takes ten to fifteen minutes. I'll let you know once I've tested it.

**Comment by Dataweaver42** [comment]
It's gone.

By the way: there are no dances in the cm3d2 emulator; but there is Yotogi.
I'll be checking later to see what happens there.

**Comment by Dataweaver42** [comment]
This issue is resolved; though in the future, you might want to consider revisiting it if you figure out a way to have DressCode return to different screens based on where it was called from.
