### ISSUE TITLE
DressCode _not_ available in Honeymoon mode

### ISSUE THREAD

**Issue by Dataweaver42** [Perdition-117/COM3D2.DressCode#12]
Well, the ability to edit your Honeymoon DressCode is available; but there's no means available to edit your Yotogi DressCode, which does occasionally come into play during a Honeymoon.

**Comment by Perdition-117** [comment]
You mean for editing your yotogi outfits while on honeymoon? Currently, the honeymoon outfit is also used for honeymoon yotogi, which I think makes sense. I considered adding an option letting you use your regular yotogi outfit for honeymoon yotogi, and I have another idea which will benefit from a similar option, but until then I suppose this is not necessary.
