### ISSUE TITLE
Access to DressCode from Dancer menu

### ISSUE THREAD

**Issue by Dataweaver42** [Perdition-117/COM3D2.DressCode#14]
In the same way that you can change a particular maid's Yotogi costume just before the session begins, could you add similar access to the editor for the Dance or Pole Dance costumes from this screen?
![img20230922133822](https://github.com/Perdition-117/COM3D2.DressCode/assets/21045510/c90b9f91-5181-48c4-9bab-d8e1decf2eaa)
This is the screen where you choose which maids will be dancers. I could see doing this by adding up to three disks vertically below the "Cancel" button, one for each dancer, that start out disabled and become enabled as you select maids from the menu at the left (and disabled again if you deselect them). Clicking one of these disks would bring up the Dance or Pole Dance editor for the appropriate maid (depending on which kind of dance you selected just before this screen), and then return you to this screen once the edit is finished with the new dance costume ready to go. Basically, the same thing you have set up for Yotogi and Honeymoon, but for Dance and Pole Dance.

**Comment by Perdition-117** [comment]
Unlikely to happen for reasons outlined in #4. (and sortof a duplicate thereof) Yotogi and honeymoon has existing logic in place that can be piggybacked off of.
