### ISSUE TITLE
Taking Location into account

### ISSUE THREAD

**Issue by Dataweaver42** [Perdition-117/COM3D2.DressCode#3]
Not a problem so much as a suggestion: could this be altered to take location into account? I'm thinking of three changes: 

1. Instead of separate Dance and Pole Dance tabs, have a single Dance tab; but under it, give a menu of choices: Default, Dance Stage, Theater, and Pole Room. (There are also some Dances that take place in a classroom, and one that takes place just outside the Empire Club, not to mention the Karaoke Room; so you'd probably want to make this list flexible based on what dances are installed.)
2. Under the Yotogi tab, have a menu of possible locations that you can have Yotogi; again, starting with a "Default" option that lets you set up choices for when nothing is provided for a given location. I could see putting the maid in a swimsuit when you take her to the beach (if you have z1 installed), or an SM outfit for the SM room, or a nightgown for her bedroom, etc.
3. Add a Work tab. For Scene Settings, the result would be almost identical to the existing ability to set up Costumes for when your Maid is working in a given Facility; the only difference would be the inclusion of a Default Facility (which applies the costume in question for any Facilities that don't have their own Dress Codes established).  For Maid Settings, it would let you override that with a specific costume for when that maid is working in that facility.

**Comment by Perdition-117** [comment]
First I will address your points. For context; I have not played through the whole story, and especially not DLC. (or don't remember things)

1. Not entirely convinced or don't fully understand. Which dances take place in the theatre, classroom or in front of the club? If they are one-off events, I don't know that a dress code is warranted. Though if the scenes can be identified using the same logic, I'll consider it.
2. Makes sense.
3. Don't fully understand which scenes this would apply to. Is it the same as the default feature, only expanded to all facilities? (and which facilities are not already supported?) Maid specific facility costume makes sense. I worry sbout potential conflict with the default feature, both logic and UI wise.

I have definitely wanted to accommodate more scenes. The scenes that are supported right now (besides being the most relevant ones) are supported because they were relatively easy to do. More granular control will require some different logic. I have an idea of how it could be done, but I don't know how well it would work. Also this UI framework is sort of a nightmare to work with, so I'm not looking forward to trying to figure that out.

All in all, this is a rather substantial request, requiring quite a bit of effort, while also no doubt providing great value. I will keep the issue open, but it probably won't happen soon.

**Comment by Dataweaver42** [comment]
It's not a high priority, compared to #1 and #5. 

The Dance stages are mostly one-offs: there's a set of aerobics "dances" that take place out front of the club; and one of KISS's partners produced a couple of dances set in a school classroom (though those dances are among the content that's going to be discontinued at the end of March).  So with that in mind, I won't hold my breath: it's probably not worth the effort to set up an open-ended locations-based menu for Dance stages. 

But on that note, I haven't yet tested your tool with any of the Dance events; just with the night-time option to perform dances at the cluib; so, for example, I don't yet know if the dancing clothes get applied to the scenes that sandwich the dances.  If they don't, they probably should: those scenes involve the maids hyping themselves up just before going onstage, or basking in the wake of a successful performance, or hyping up the audience between performances; all are cases where the maid's Dancing attire ought to be used. Again, I haven't gotten to the first concert with DressCode in play yet; so it may not be a problem at all. We'll see. 

As for facilities, they already implement the equivalent of your Scene Settings (but on a per-Facility basis). The primary thing I'm looking for is the ability to be Maid-specific _as well as_ Facility-specific; but if you can also implement a "catch-all Dress Code" for a given maid that applies to all Facilities that haven't been specifically tailored, that would give me the option of setting the maid's regular attire as some sort of casual wear while setting her "work attire" to an appropriate maid outfit.

**Comment by Perdition-117** [comment]
I actually don't think I have tested any story/event dance, either. I should do that. If it's just a non interactive dance event, it probably won't do anything. For story rhythm game dances, it might.

From what you describe, from a gameplay perspective, I can see that it might make sense for dance costumes to apply.

Regarding facilities; I can see the value in it, but I'm not crazy about the overlap with the default feature. When is it those costumes are applied? Is it only when picking the "watch her work" schedule option?

**Comment by Dataweaver42** [comment]
That; and I think that Life Mode also uses the Facility costumes.

**Comment by Dataweaver42** [comment]
Update: I just completed the HotStart! Event, utilizing DressCode to put the dancers in costume. It turns out that they _weren't_ in costume during the HotStart cut scenes; just during the dances themselves. It was a bit jarring. 

I hope there's an easy way to identify events that include dances, so that the girls can be in uniform throughout. I wouldn't have a clue where to begin on that, though.

**Comment by Dataweaver42** [comment]
Clarifying: the one ask I have is to leverage the Facility Costumes to be able to be maid-specific. I don't really need the rest.

**Comment by Perdition-117** [comment]
You're referring to scenes like these, right? That is probably not going to happen. I can definitely see that it would be expected, but I don't think there's an easy way to make it work without doing something like finding all the event IDs, which frankly I'm not going to do. I'll look into it a bit. Maybe there exists some way of which I am unaware.

![img20230319155337](https://user-images.githubusercontent.com/87424475/226184391-7cbfe0db-ed4e-45c4-a480-78498679db04.png)

The yotogi and work stuff is more doable from a technical standpoint (probably), but requires some thought.

**Comment by Dataweaver42** [comment]
I've got a possible solution to this: add some limited per-scene functionality. What I'm thinking is something like this: 

1. When a scene starts, check a database to see if there are any DressCodes for the scene. If so, apply them. 
2. Add a tool that lets the player choose one of the existing DressCodes for each of the maids in the scene. The choices should be “Dance”, “Pole Dance”, “Yotogi”, “Personal Mode”, “Honeymoon”, or “No Dress Code”. Basically, the set of available DressCodes for the maid, plus a “No DressCode” option. This does _not_ include the ability to customize the DressCode; only to choose which one, if any, to apply. Dance scenes default to Dance; Pole Dance scenes default to “Pole Dance”; Yotogi scenes default to “Yotogi”; Personal Mode scenes default to “Personal Mode”; Honeymoon scenes default to “Honeymoon”; and all other scenes default to “No DressCode”. 
3. Whenever the player makes a selection from that tool, apply the appropriate costume immediately and record the choice for future viewings of the scene. 
4. At the end of the scene, revert to the original costume. 

For Yotogi scenes, I would disable the “Edit Costume” button: the ability to set up a Yotogi DressCode renders it unnecessary. 

That leaves only the maid-specific Facility DressCodes.

**Comment by Perdition-117** [comment]
Don't fully understand what you are proposing. Are you thinking of some sort of catch all functionality for non supported scenes? Any examples?

The problem with most scenes is that they use a generic identifier.

**Comment by Dataweaver42** [comment]
More or less, yes. Giving the player the ability to choose which DressCode to use in a scene lets him tailor the experience to match his preferences. It's a solution intended to get around the amount of work it would take the designer (you) to go through the scenes and decide which DressCode applies to each. 

I was thinking in terms of the scene that you provided a screen capture of in this thread: as a player, I'd want to put the maids in their Dance DressCodes; so with the proposed tool, once the scene begins I'd select each maid in the scene and set her DressCode to “Dance”. And for the remainder of the scene, I could have all of the maids that are present in their Dance outfits. 

If there isn't a way to easily track which scene you're dealing with, that severely reduces the benefit of this idea; though it doesn't render it useless.

**Comment by Perdition-117** [comment]
Alright. So yeah, the problem was always one of scene identification. The game uses Unity scenes, and there are individual scenes for all supported DressCode scenes. In fact, I think every song/dance has its own scene. All events use a single shared scene `SceneADV`, however.

There is no good solution to this as far as I'm aware, and what solution remains is not really something I want to spend time on.

Closing for now.
