### ISSUE TITLE
Transferred maids can't DressCode for Yotogi

### ISSUE THREAD

**Issue by Dataweaver42** [Perdition-117/COM3D2.DressCode#7]
![img20230316221954](https://user-images.githubusercontent.com/21045510/225793976-315a8106-10e1-4642-bc6a-277f97eeeb94.png)
This is Kotogi Hikari, the first maid that I transferred from CM3D2 to COM3D2. Notice how the Yotogi button is dark, as if she was an Extra.  She's not; and she's also perfectly capable of performing Yotogi. Furthermore, the DressCode Scene Settings apply to her just fine when she does so.  I'm merely incapable of setting up any Maid Settings for her during Yotogi.

**Comment by Perdition-117** [comment]
I am unable to test this, but I found what I believe should be the fix.
