### ISSUE TITLE
Settings reset

### ISSUE THREAD

**Issue by Dataweaver42** [Perdition-117/COM3D2.DressCode#8]
In the 1.1.0 beta, upon entering DressCode, I found that all of the maids were reset to Default; I had to manually go in and change everything back to Scene or Personal where appropriate.

**Comment by Perdition-117** [comment]
Hm, that's strange. I don't remember changing anything that would affect that. I don't suppose you have a copy of your old configuration file and/or are able to reproduce the issue?

**Comment by Dataweaver42** [comment]
>
> Hm, that's strange. I don't remember changing anything that would affect
> that. I don't suppose you have a copy of your old configuration file and/or
> are able to reproduce the issue?
>
I'll try reinstalling the 1.00 version, and then coming back to 1.10 to see
if I can get it to happen again.

**Comment by Dataweaver42** [comment]
I think this might also have something to do with how DressCode interacts with save files. I've had to re-establish DressCode settings when beginning a new game; but when I do, the existing costumes are implemented. 

Oddly, transferred maids don't have this issue at all: when they arrive at the new club, all of their DressCode settings are as they had been in prior run-throughs of the game.

**Comment by Perdition-117** [comment]
Maids have globally unique IDs assigned to them, which are used for the maid specific outfits. New maids get new IDs, but it is possible that transferred maids retain their CM3D2 IDs, meaning they will have the same IDs every time you transfer them.

Scene settings/outfits will carry over to new saves as they are not bound to any ID.

**Comment by Perdition-117** [comment]
Have your concerns been cleared up, or do you still feel there is an issue?

**Comment by Dataweaver42** [comment]
My concerns have been resolved. Frankly, I think this is ready for prime time now.

**Comment by Perdition-117** [comment]
Thanks for all your feedback!
