### ISSUE TITLE
Colors getting messed up

### ISSUE THREAD

**Issue by Dataweaver42** [Perdition-117/COM3D2.DressCode#9]
After a number of edits, this happened:
![Screenshot 2023-09-20 055754](https://github.com/Perdition-117/COM3D2.DressCode/assets/21045510/534b7a43-2a84-436d-bead-2b32461885f9)
It didn't affect the resulting edit as far as I can tell. 
The next time I attempted to edit a DressCode costume after this, I got all black except the controls. It extended beyond just DressCode; once things fell apart, I was getting the black background everywhere. 

It may be an unrelated problem that just happened to manifest while I was in DressCode; I don't know yet.

**Comment by Perdition-117** [comment]
Oh dear! Haven't seen anything like that before. If you get it again, please submit your game log. You can find it at `COM3D2\COM3D2x64_Data\output_log.txt`.

**Comment by Dataweaver42** [comment]
[output_log.txt](https://github.com/Perdition-117/COM3D2.DressCode/files/12675424/output_log.txt)
It just happened again.

**Comment by Perdition-117** [comment]
Hm, well, I can see that there's an error regarding a missing SceneCapture preset, which seems relevant given the graphical nature of the issue.

**Comment by Dataweaver42** [comment]
I'll also note that it sometimes takes a while for the problem to kick in.
It's only happened after five done a dozen or so consecutive edits in
DressCode, without leaving DressCode. I suspect a memory leak.

**Comment by Dataweaver42** [comment]
I haven't seen this problem at all lately; the latest beta seems to have fixed it, or there was some unrelated cause.
